[package]
name = "amll-player"
version = "0.0.0"
description = "AMLL Player"
authors = ["you"]
license = ""
repository = ""
edition = "2024"

[lib]
name = "amll_player_lib"
crate-type = ["staticlib", "cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1.0"
anyhow-tauri = "1.0.0"
base64 = "0.22.1"
crossbeam-channel = "0.5.15"
futures = "0.3.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
symphonia = { version = "^0.5", features = ["all", "opt-simd"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "process",
    "sync",
    "time",
] }
tokio-tungstenite = "0.27"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

tauri = { version = "2", features = ["devtools"] }
tauri-plugin-dialog = { version = "2" }
tauri-plugin-fs = { version = "2" }
tauri-plugin-opener = { version = "2" }
tauri-plugin-os = { version = "2" }
tauri-plugin-shell = { version = "2" }

amll-player-core = { path = "../../player-core" }
ws-protocol = { path = "../../ws-protocol" }
tauri-plugin-http = "2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-avf-audio = "0.3.1"

[target.'cfg(target_os = "windows")'.dependencies]
smtc-suite = "2"
webview2-com = "0.38"

[target.'cfg(target_os = "android")'.dependencies]
cpal = { version = "0.16", features = ["oboe-shared-stdcxx"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = { version = "2" }
tauri-plugin-updater = { version = "2" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

ffmpeg-backend = ["amll-player-core/ffmpeg"]

[profile.dev.package."*"]
opt-level = 1

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
debug = false
