[package]
name = "amll-player"
version = "0.0.0"
description = "AMLL Player"
authors = ["you"]
license = ""
repository = ""
edition = "2024"

[lib]
name = "amll_player_lib"
crate-type = ["staticlib", "cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
# tauri-plugin-os = "2.0.0-rc"
# tauri-plugin-fs = "2.0.0-rc"
# tauri-plugin-dialog = "2.0.0-rc"
# tauri = { git = "https://github.com/tauri-apps/tauri.git", features = [ "devtools" ] }
tauri-plugin-os = { version = "2" }
tauri-plugin-fs = { version = "2" }
tauri-plugin-dialog = { version = "2" }
tauri-plugin-shell = { version = "2" }
anyhow-tauri = "1.0.0"

base64 = "^0.22"
image = "^0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-tungstenite = "0.27"
anyhow = "1.0.72"
futures = "0.3.28"
symphonia = { version = "^0.5", features = ["all", "opt-simd"] }
ws-protocol = { path = "../../ws-protocol" }
amll-player-core = { path = "../../player-core" }
amll-lyric = { path = "../../lyric" }
tokio = { version = "1.45.1", features = [
    "time",
    "macros",
    "process",
    "sync",
    "rt",
    "rt-multi-thread",
] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
fxhash = "0.2.1"

[target.'cfg(target_os = "windows")'.dependencies]
webview2-com = "*"
smtc-suite = "1"
[target.'cfg(target_os = "android")'.dependencies]
cpal = { version = "*", features = ["oboe-shared-stdcxx"] }
tracing-android = "^0.2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "^2"
# tauri-plugin-updater = "2.0.0-rc"
tauri-plugin-updater = { version = "2" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
ffmpeg-backend = ["amll-player-core/ffmpeg"]

[profile.dev.package."*"]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "s"
debug = false
strip = true

# [patch.crates-io]
# tauri = { git = "https://github.com/tauri-apps/tauri.git" }
