[package]
name = "ws-protocol"
version = "0.0.2"
authors = ["SteveXMH <39523898+Steve-xmh@users.noreply.github.com>"]
edition = "2024"
repository = "https://github.com/Steve-xmh/applemusic-like-lyrics"
description = "一个歌词播放器协议库，用于不同播放软件与实现本协议的歌词播放器同步播放进度和播放信息"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
binrw = "^0.14"
serde_bytes = "^0.11"
anyhow = "^1.0"

[dev-dependencies]
serde_json = "^1.0"
tungstenite = "^0.26"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "^0.2" }
serde-wasm-bindgen = { version = "^0.6" }
console_error_panic_hook = { version = "^0.1", optional = true }
wee_alloc = { version = "^0.4", optional = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "^0.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false