name: 构建 AMLL Player Tauri 桌面版本
on:
  push:
    branches:
      - full-refractor
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean-pre-release:
    name: 删除预发布版本的构建产物
    runs-on: ubuntu-latest
    steps:
      - name: 删除预发布版本的构建产物
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          assets: |
            *.*
          tag: ${{ github.ref_name }}-player-dev
          fail-if-no-assets: false
          fail-if-no-release: false
  build-tauri-desktop:
    name: 构建 Tauri 桌面版本
    needs: clean-pre-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            args: ""
            name: linux
            arch: x86_64
            features: "--features ffmpeg-next/build" # ffmpeg-next 在 linux 上的支持比较好，可以直接构建
          - platform: windows-latest
            args: ""
            name: windows
            arch: x86_64
            features: ""
          - platform: windows-latest
            args: "--target aarch64-pc-windows-msvc"
            name: windows
            arch: aarch64
            features: ""
          - platform: macos-latest # arm64 二进制包
            args: "--target aarch64-apple-darwin"
            name: macOS
            arch: aarch64
            features: ""
          - platform: macos-latest # x86 二进制包
            args: "--target x86_64-apple-darwin"
            name: macOS
            arch: x86_64
            features: ""
          - platform: macos-latest # 通用二进制包
            args: "--target universal-apple-darwin"
            name: macOS
            arch: universal
            features: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        name: 克隆仓库
        with:
          fetch-depth: 0 # 为了正确生成开发版本号码

      - name: 安装 PNPM
        uses: pnpm/action-setup@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: |
            wasm32-unknown-unknown,${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || (matrix.platform == 'windows-latest' && matrix.arch == 'aarch64') && 'aarch64-pc-windows-msvc' || '' }}

      - name: 安装 vcpkg
        if: matrix.platform == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git D:/vcpkg
          D:/vcpkg/bootstrap-vcpkg.bat
          D:/vcpkg/vcpkg integrate install
        shell: cmd

      - name: 使用 vcpkg 安装 FFmpeg
        if: matrix.platform == 'windows-latest'
        run: |
          $VCPKG_ROOT = "D:/vcpkg"
          if ("${{ matrix.arch }}" -eq "aarch64") {
            ./vcpkg install ffmpeg:arm64-windows-static-md
          } else {
            ./vcpkg install ffmpeg:x64-windows-static-md
          }
        working-directory: D:/vcpkg
        shell: powershell

      - name: 设置 vcpkg 环境变量
        if: matrix.platform == 'windows-latest'
        run: |
          echo "VCPKG_ROOT=D:/vcpkg" >> $GITHUB_ENV
        shell: bash

      - name: 安装 sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: 配置 sccache
        run: |
          echo "RUSTC_WRAPPER=${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}" >> $GITHUB_ENV
          echo "ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}" >> $GITHUB_ENV
        shell: bash

      # macOS 自带的 Xcode LLVM 不支持 WASM 目标
      - name: "macOS: 安装 LLVM 和 Clang"
        uses: KyleMayes/install-llvm-action@v2
        if: matrix.platform == 'macos-latest'
        with:
          version: "15"

      - name: 安装 FFmpeg 依赖并配置环境 (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          brew install ffmpeg pkg-config yasm nasm
          if [[ "${{ matrix.arch }}" == "x86_64" || "${{ matrix.arch }}" == "universal" ]]; then
            arch -x86_64 brew install ffmpeg pkg-config yasm nasm
          fi

          if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
            echo "PKG_CONFIG_PATH=/usr/local/opt/ffmpeg/lib/pkgconfig" >> $GITHUB_ENV
            echo "LDFLAGS=-L/usr/local/opt/ffmpeg/lib" >> $GITHUB_ENV
            echo "CPPFLAGS=-I/usr/local/opt/ffmpeg/include" >> $GITHUB_ENV
          fi

      - name: 安装 Tauri 和 FFmpeg 所需系统依赖（仅 Linux）
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          # tauri deps
          sudo apt-get install -y libasound2-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf
          # ffmpeg deps
          sudo apt-get install -y build-essential pkg-config yasm nasm git

      - name: 安装 wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.1"

      - name: 构建 AMLL Full React 包
        run: |
          pnpm i --frozen-lockfile --ignore-scripts
          pnpm nx build player
        env:
          AMLL_GITHUB_IS_ACTION: true

      - name: 生成开发构建版本号
        run: |
          node ./packages/player/scripts/gen-dev-version.mjs

      - name: 构建 AMLL Player 程序并发布自动构建
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: packages/player
          tagName: ${{ github.ref_name }}-player-dev
          includeUpdaterJson: true
          releaseName: AMLL Player ${{ github.ref_name }} branch development build
          releaseBody: |
            Latest ${{ github.ref_name }} branch development build.
            最新 ${{ github.ref_name }} 分支开发调试构建。
            Development version may be unstable and may not work properly, please only for test purpose.
            开发版本可能不稳定且可能无法正常工作，请仅用于测试目的。

            Latest commits (最新提交): ${{ github.event.head_commit.message }}
          prerelease: true
          args: ${{ matrix.args }} ${{ matrix.features }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: 上传产物到 Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AMLL Player ${{matrix.name}}-${{matrix.arch}}
          path: |
            packages/player/src-tauri/target/**/release/bundle/**/*
            packages/player/src-tauri/target/**/release/amll-player.exe
            packages/player/src-tauri/target/**/release/amll-player

  build-tauri-android:
    name: 构建 Tauri 安卓移动版本
    needs: clean-pre-release

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 克隆仓库
        with:
          fetch-depth: 0 # 为了正确生成开发版本号码
      - name: 安装 PNPM
        uses: pnpm/action-setup@v4
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: "x86_64-unknown-linux-gnu,x86_64-linux-android,i686-linux-android,aarch64-linux-android,arm-linux-androideabi,armv7-linux-androideabi,thumbv7neon-linux-androideabi"
      - name: 安装 wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.1"
      - name: 安装 wasm32 目标
        run: rustup target add wasm32-unknown-unknown
      - name: 安装 sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: 配置 sccache
        run: |
          echo "RUSTC_WRAPPER=${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "ACTIONS_CACHE_URL=${{ env.ACTIONS_CACHE_URL }}" >> $GITHUB_ENV
          echo "ACTIONS_RUNTIME_TOKEN=${{ env.ACTIONS_RUNTIME_TOKEN }}" >> $GITHUB_ENV
        shell: bash
      - name: 设置 Android SDK/NDK
        uses: android-actions/setup-android@v3
      - name: 安装 NDK
        run: sdkmanager --install "ndk;27.2.12479018"
      - name: 构建 AMLL Full React 包
        run: |
          pnpm i --frozen-lockfile --ignore-scripts
          pnpm lerna run build --concurrency=1 --stream --scope player
        env:
          AMLL_GITHUB_IS_ACTION: true
      - name: 生成开发构建版本号
        run: |
          node ./packages/player/scripts/gen-dev-version.mjs
      - name: 构建 AMLL Player 安卓移动版程序
        env:
          CARGO_NDK_ANDROID_PLATFORM: 26
        run: |
          sccache --show-stats
          export NDK_HOME=$ANDROID_NDK_HOME
          export JAVA_HOME=$JAVA_HOME_17_X64
          pnpm -F player tauri android build --split-per-abi
          sccache --show-stats
      - name: 上传产物到 Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AMLL Player Android Universal
          path: |
            packages/player/src-tauri/gen/android/app/build/outputs/**/*.apk
            packages/player/src-tauri/gen/android/app/build/outputs/**/*.aab
